In [ ]:

import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/supply_chain - supply_chain.csv')
df.head(2)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579

In [ ]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [ ]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [ ]:
df['Product type'].unique()

array(['haircare', 'skincare', 'cosmetics'], dtype=object)

In [ ]:
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default ='plotly_white'

In [ ]:
fig=px.scatter(df,
               x='Price',
               y='Revenue generated',
               color='Product type',
               hover_data=['Number of products sold'],
               trendline='ols')
fig.show()

In [ ]:
sales_data=df.groupby('Product type')['Number of products sold'].sum().reset_index()
sales_data

  Product type  Number of products sold
0    cosmetics                    11757
1     haircare                    13611
2     skincare                    20731

In [ ]:
pie_chart=px.pie(sales_data,
                 names='Product type',
                 values='Number of products sold',
                 title='Sales by Product Type',
                 hover_data=['Number of products sold'],
                 hole=0.5,
                 color_discrete_sequence=px.colors.qualitative.Pastel
                 )
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

In [ ]:
total_revenue=df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
total_revenue

  Shipping carriers  Revenue generated
0         Carrier A      142629.994607
1         Carrier B      250094.646988
2         Carrier C      184880.177145

In [ ]:
fig=go.Figure()
fig.add_trace(go.Bar(
    x=total_revenue['Shipping carriers'],
    y=total_revenue['Revenue generated'],
))
fig.update_layout(
    title='Total Revenue by Shipping Carriers',
    xaxis_title='Shipping Carriers',
    yaxis_title='Total Revenue'
)
fig.show()

In [ ]:
deffect_target=df.groupby('Product type')['Defect rates'].sum().reset_index()
deffect_target

  Product type  Defect rates
0    cosmetics     49.901461
1     haircare     84.427107
2     skincare     93.387231

In [ ]:
pie_chart1=px.pie(deffect_target,
                 names='Product type',
                 values='Defect rates',
                 title='Defect Rates by Product Type',
                 hover_data=['Defect rates'],
                 hole=0.5,
                 #color_discrete_sequence=px.colors.qualitative.Pastel
                 )
pie_chart1.update_traces(textposition='inside',textinfo='percent+label')
pie_chart1.show()

In [ ]:
avg_shipping_time=df.groupby('Product type')['Shipping times'].mean().reset_index()
avg_shipping_time

  Product type  Shipping times
0    cosmetics        6.576923
1     haircare        5.617647
2     skincare        5.325000

In [ ]:
fig=px.pie(avg_shipping_time,
           names='Product type',
           values='Shipping times',
           title='Average Shipping Time by Product Type',
           hover_data=['Shipping times'],
           hole=0.3,
           color_discrete_sequence=px.colors.qualitative.Pastel
           )
fig.update_traces(textposition='inside',textinfo='percent+label')
fig.show()

In [ ]:
avg_lead_time=df.groupby('Product type')['Lead times'].mean().reset_index()
avg_lead_time

  Product type  Lead times
0    cosmetics   15.384615
1     haircare   15.529412
2     skincare   16.700000

In [ ]:
avg_manufacturing_costs=df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
avg_manufacturing_costs

  Product type  Manufacturing costs
0    cosmetics            43.052740
1     haircare            48.457993
2     skincare            48.993157

In [ ]:
result=pd.merge(avg_manufacturing_costs,avg_lead_time,on='Product type')
#result.rename(columns={'Lead times':'Average Lead Time','Manfacturing costs':'Average Manufacturing Costs'},inplace=True)
result.rename(columns={'Lead times':'Average Lead Time','Manufacturing costs':'Average Manufacturing Costs'},inplace=True)
result

  Product type  Average Manufacturing Costs  Average Lead Time
0    cosmetics                    43.052740          15.384615
1     haircare                    48.457993          15.529412
2     skincare                    48.993157          16.700000

In [ ]:
#analyzing sku
revenue_chart=px.line(df,x='SKU',y='Revenue generated',title='Revenue Generated by SKU')
revenue_chart.show()

In [ ]:
#stocks available in sku
stock_chart=px.line(df,x='SKU',y='Stock levels',title='Stocks levels by SKU')
stock_chart.show()

In [ ]:
# order quantity
order_quantity_chart=px.bar(df,x='SKU',y='Order quantities',title='Order Quantities by SKU')
order_quantity_chart.show()

In [ ]:
# cost analysis
shipping_cost_chart=px.bar(df,x='Shipping carriers',y='Shipping costs',title='Shipping Costs by Carriers')
shipping_cost_chart.show()

In [ ]:
df['Transportation modes'].unique()

array(['Road', 'Air', 'Rail', 'Sea'], dtype=object)

In [ ]:
#cost distribution by transportation mode in pie chart
# use group by on mode and cost
trans_mode=df.groupby('Transportation modes')['Costs'].mean().reset_index()
trans_mode
transportation_mode_chart=px.pie(trans_mode,names='Transportation modes',values='Costs',title='Transportation Costs by Mode',hole=0.4)
transportation_mode_chart.show()